extends Node

var cutscene_drive = [
{"speaker":"Ryan", "line":"Okay, remind me again why we thought going this far into nowhere was a good idea?"},
{"speaker":"Jake", "line":"Because you said you wanted an adventure."},
{"speaker":"Ryan", "line":"I said I wanted an adventure. I didn't say I wanted to die."},
{"speaker":"Emma", "line":"You say that every time something takes more than twenty minutes."},
{"speaker":"Ryan", "line":"Because every time something takes more than twenty minutes, something terrible happens."},
{"speaker":"Alex", "line":"Statistically, that's not how—"},
{"speaker":"Ryan", "line":"Alex, please don't ruin my argument with statistics."},
{"speaker":"Ethan", "line":"Guys, relax. We're almost there."},
{"speaker":"Jake", "line":"Noah, you sure your cabin is actually here?"},
{"speaker":"Noah", "line":"Yeah."},
{"speaker":"Ethan", "line":"You don't sound very sure."},
{"speaker":"Noah", "line":"I haven't been here in a long time."},
{"speaker":"Emma", "line":"How long?"},
{"speaker":"Noah", "line":"...Three years."},
{"speaker":"Ryan", "line":"That's reassuring."},
{"speaker":"Ethan", "line":"Noah?"},
{"speaker":"Noah", "line":"We're taking the next turn."},
]
var barks_road = [
{"speaker":"Ethan", "line":"Everyone okay?"},
{"speaker":"Ryan", "line":"If something jumps out of those trees, I'm blaming Noah."},
{"speaker":"Alex", "line":"We're completely off the mapped road."},
{"speaker":"Jake", "line":"You hear that?"},
{"speaker":"Jake", "line":"Never mind."},
]
var cutscene_sign = [
{"speaker":"Emma", "line":"Noah."},
{"speaker":"Noah", "line":"What?"},
{"speaker":"Emma", "line":"You said there was nothing out here."},
{"speaker":"Noah", "line":"There wasn't."},
{"speaker":"Alex", "line":"Blackwood Research Facility. It's not on the map."},
{"speaker":"Ryan", "line":"Great. Secret mountain laboratory."},
{"speaker":"Jake", "line":"Maybe it's abandoned."},
{"speaker":"Noah", "line":"It is."},
{"speaker":"Emma", "line":"You've been there."},
{"speaker":"Noah", "line":"My brother worked there."},
{"speaker":"Ryan", "line":"You never mentioned a brother."},
{"speaker":"Noah", "line":"I don't talk about him."},
{"speaker":"Emma", "line":"Why?"},
{"speaker":"Noah", "line":"Because he's dead."},
{"speaker":"Ethan", "line":"Let's just go to the cabin."},
{"speaker":"Noah", "line":"We shouldn't be here."},
]
var cutscene_cabin_arrival = [
{"speaker":"Ryan", "line":"Okay... This is definitely not what I imagined."},
{"speaker":"Jake", "line":"It's fine."},
{"speaker":"Ryan", "line":"The front door looks like it hasn't been opened since dinosaurs existed."},
{"speaker":"Alex", "line":"That's not how time works."},
{"speaker":"Ryan", "line":"You know what I mean."},
{"speaker":"Emma", "line":"Guys... There's someone inside."},
{"speaker":"Jake", "line":"What?"},
{"speaker":"Emma", "line":"There's someone inside."},
{"speaker":"Ethan", "line":"Wait."},
{"speaker":"Noah", "line":"Don't."},
{"speaker":"Ethan", "line":"Why?"},
{"speaker":"Noah", "line":"Just... don't."},
]
var cutscene_photos = [
{"speaker":"Emma", "line":"That's me."},
{"speaker":"Ryan", "line":"Okay... creepy."},
{"speaker":"Jake", "line":"That's Ethan."},
{"speaker":"Alex", "line":"These were taken recently."},
{"speaker":"Noah", "line":"No. This can't be here."},
{"speaker":"Ethan", "line":"What?"},
{"speaker":"Emma", "line":"You recognize this place?"},
{"speaker":"Noah", "line":"We shouldn't be here."},
{"speaker":"Ethan", "line":"Noah."},
]
var cutscene_facility = [
{"speaker":"Ryan", "line":"Yeah... Definitely abandoned."},
{"speaker":"Alex", "line":"Power is still running."},
{"speaker":"Jake", "line":"How?"},
{"speaker":"Alex", "line":"I don't know."},
{"speaker":"Noah", "line":"We need to leave."},
{"speaker":"Ethan", "line":"Why?"},
{"speaker":"Noah", "line":"Because I said so."},
{"speaker":"Emma", "line":"That's not an answer."},
{"speaker":"Alex", "line":"Guys."},
{"speaker":"[TERMINAL]","line":"BLACKWOOD RESEARCH FACILITY / SYSTEM STATUS: ACTIVE / GROUP 27 / STATUS: UNKNOWN"},
{"speaker":"Ryan", "line":"What's Group 27?"},
{"speaker":"[RADIO]","line":"If the subject escapes... do not approach it."},
{"speaker":"Noah", "line":"Elias..."},
{"speaker":"Emma", "line":"Who is Elias?"},
]
var cutscene_final = [
{"speaker":"Ryan", "line":"Uh... Please tell me somebody paid the electricity bill."},
{"speaker":"Ethan", "line":"Everyone stay where you are."},
{"speaker":"Emma", "line":"Where's Noah?"},
{"speaker":"Alex", "line":"He was just here."},
{"speaker":"Jake", "line":"What was that?"},
{"speaker":"Emma", "line":"I don't know."},
{"speaker":"Ryan", "line":"That's not an animal."},
{"speaker":"[RADIO]","line":"Six... ...subjects... ...detected."},
{"speaker":"Noah", "line":"We need to leave."},
{"speaker":"Ethan", "line":"Now."},
]
var choice_1 = {
"prompt": "What do you do?",
"option_a": "We came here for a weekend. Let's just go. [CABIN]",
"option_b": "We should find out what this place is. [BLACKWOOD]"
}
